version: "3"

services:
  nats-servers:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservicios-432920/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-servers:4222

  auth-ms:
    build:
      context: ./auth-ms_v2
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservicios-432920/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=${AUTH_DATABSE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservicios-432920/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservicios-432920/image-registry/orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-ms:
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservicios-432920/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-servers:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_TESTING_ENDPOINT_SECRET=${STRIPE_TESTING_ENDPOINT_SECRET}
